// Add the Basic Settings tab in basic settings form.
config_translations_example.basic_settings:
  route_name: config_translations_example.basic_settings
  title: Basic Settings
  base_route: config_translations_example.basic_settings

// Add the Medium Settings tab in Medium settings form.
config_translations_example.medium_settings:
  route_name: config_translations_example.medium_settings
  title: Medium Settings
  base_route: config_translations_example.medium_settings

// Add the Advanced Settings tab in Advanced settings form.
config_translations_example.advanced_settings:
  route_name: config_translations_example.advanced_settings
  title: Advanced Settings
  base_route: config_translations_example.advanced_settings
