config_translations_example.basic_settings:
  title: Basic Settings
  base_route_name: config_translations_example.basic_settings
  names:
    - config_translations_example.basic_settings

config_translations_example.medium_settings:
  title: Medium Settings
  base_route_name: config_translations_example.medium_settings
  names:
    - config_translations_example.medium_settings

config_translations_example.advanced_settings:
  title: Advanced Settings
  base_route_name: config_translations_example.advanced_settings
  names:
    - config_translations_example.advanced_settings